---
framework: mocha
postMerge:
  pattern:
    - "./packages/enzyme-test-suite/build/*spec.js"
preMerge:
  pattern:
    - "./packages/enzyme-test-suite/build/*spec.js"
preRun:
     command:
        - npm run clean-node-modules
        - npm install 
        - npm run postinstall
        - npm run build
        - npm run test:all
postRun:
     command:
        - node --version
version: 1.0
