---
framework: mocha
postMerge:
  pattern:
    - "./packages/enzyme-test-suite/build/*spec.js"
preMerge:
  pattern:
    - "./packages/enzyme-test-suite/build/*spec.js"
preRun:
     command:
        - npm install 
        - npm install mocha
        - npm run build
        - npm run react 13
postRun:
     command:
        - node --version

configFile: karma.conf.js
tier: small
version: 1.0
